// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test1', async function() {
    await driver.get("http://localhost:4200/calculator")
    await driver.manage().window().setRect({ width: 1878, height: 936 })
    await driver.findElement(By.id("1")).click()
    await driver.findElement(By.id("2")).click()
    await driver.findElement(By.id("+")).click()
    await driver.findElement(By.id("4")).click()
    await driver.findElement(By.id("5")).click()
    await driver.findElement(By.id("=")).click()
    await driver.findElement(By.id("display")).getText().then(function(text) {
      assert.equal(text, "12+45=57")
    }
  )})
})
