// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test1', async function() {
    await driver.get("http://localhost:4200/calculator")
    await driver.manage().window().setRect({ width: 1878, height: 936 })
    await driver.findElement(By.css(".calculator__key:nth-child(11)")).click()
    await driver.findElement(By.css(".calculator__key:nth-child(12)")).click()
    await driver.findElement(By.css(".calculator__key:nth-child(1)")).click()
    await driver.findElement(By.css(".calculator__key:nth-child(8)")).click()
    await driver.findElement(By.css(".calculator__key:nth-child(9)")).click()
    await driver.findElement(By.css(".calculator__key--enter")).click()
    await driver.findElement(By.css(".calculator__output")).click()
    assert.equal(await driver.findElement(By.css(".calculator__output")).getText(), "12+45=57")
  })
})
